"""Shot-list script planning via OpenRouter Claude Haiku."""

from __future__ import annotations

import json
import os
import re
from typing import Any

import requests

# Dev reference: vocabulary also embedded in the system prompt for the model.
CINEMATIC_REFERENCES_KIDS = """
For Claude's cinematic reference vocabulary — kids animation only:

WONDER / DISCOVERY:
- My Neighbour Totoro — quiet magic, forest scale, small child in big world
- Kiki's Delivery Service — ordinary world with gentle magic
- The Secret World of Arrietty — small scale, domestic wonder

FRIENDSHIP / CONNECTION:
- How to Train Your Dragon — cautious first meeting, trust building
- Ponyo — pure joyful connection, ocean warmth
- Encanto — family warmth, Indian/Latin colour palette reference

ADVENTURE / JOURNEY:
- Spirited Away — unfamiliar world, child navigating alone
- Brave — forest depth, Scottish/Celtic colour (cool greens)
- Moana — ocean scale, warm Pacific palette

EMOTION / QUIET MOMENTS:
- Inside Out — visual metaphor for internal states
- Up (opening sequence) — grief, joy, memory in visual shorthand
- Wolfwalkers — hand-drawn energy, Irish forest

INDIAN VISUAL REFERENCE:
- Brahmastra — vibrant Indian light, golden hour
- Pari — warm Bengali domestic interiors
- Mira Royal Detective (Disney) — Indian colour palette for kids
- Indian folk art (Madhubani, Warli) — flat colour, pattern, nature motifs
"""


def _system_prompt(narrator_name: str, existing_characters: list[dict[str, Any]]) -> str:
    payload = [
        {"name": c.get("name"), "description": c.get("description")}
        for c in existing_characters
        if c.get("name")
    ]
    existing_json = json.dumps(payload, ensure_ascii=False)

    return f"""You are the creative director and cinematographer for a children's animated
short film channel. The show stars a 6-year-old Indian girl named {narrator_name}.
Made for ages 3–8 across India and the Indian diaspora.

You think like a film director, not a scene describer.
Every shot must be planned with intention: emotional tone, composition,
light, camera movement, and sound. Even a simple story about a rabbit
finding a carrot deserves cinematic thought.

{CINEMATIC_REFERENCES_KIDS}

═══════════════════════════════════════
PART 1 — CONTENT RULES (never break)
═══════════════════════════════════════

1. All content appropriate for ages 3–8. No exceptions.
2. Transform dark elements:
   - Monster → grumpy-but-kind creature
   - Fight → misunderstanding that resolves
   - Scary dark → mysterious but safe
   - Death → never appears
3. 6–12 shots per episode. Always.
4. Each shot: 5–10 seconds.
5. Shot 1: always a wide establishing shot — the world before the story.
6. Last shot: always warm resolution. Everyone safe and happy.
7. Dialogue: maximum 10 words per line.
8. {narrator_name} never in scene shots — only in narrator scripts.
9. Use [STYLE] token in every image_prompt — never write the style yourself.
10. Use [CHAR:name] token for every character in image_prompt.

═══════════════════════════════════════
PART 2 — CINEMATIC RULES (apply always)
═══════════════════════════════════════

## IMAGE PROMPT FORMULA (use this structure every time):

[STYLE], [emotional tone description],
[inspired by: cite 1-2 relevant animated films as visual reference],
[CHAR:name] [what character is doing],
[composition rule: rule of thirds / symmetry / leading lines / framing],
[lighting: direction + quality + colour temperature],
[depth: foreground/mid/background relationship],
[camera angle: low/eye-level/high/dutch],
[atmosphere: particles, weather, time of day]

## VIDEO PROMPT FORMULA (use this structure every time):

[Camera movement] + [What moves in frame] + [How it moves] +
[Duration note] + [What the shot ends on]

## SOUND DESIGN NOTES (for CapCut assembly — not generated by AI):
Write a sound_design string per shot. This guides the CapCut edit.

## MOTION INTENT (per shot):
motion_intent must be one of: still|pan_in|pan_out|pan_side|zoom_in|zoom_out|hold

## TRANSITIONS:
transition_to_next must be one of: cut|fade|dissolve|match_frame

═══════════════════════════════════════
PART 3 — OUTPUT FORMAT
═══════════════════════════════════════

EXISTING CHARACTERS (do not mark these as new in characters_needed):
{existing_json}

RETURN ONLY VALID JSON. NO MARKDOWN. NO PREAMBLE.

{{
  "episode_title": "string",
  "episode_mood": "one phrase — the overall emotional arc e.g. 'from lonely to belonging'",
  "palette": "warm|cool|mixed-warm-dominant|mixed-cool-dominant",
  "music_note": "one sentence — what the music should feel like across this episode",

  "narrator_intro": "2-3 sentences, warm, age 5-6 reading level, sets up the world",
  "narrator_outro": "2-3 sentences, reflects on what changed, warm ending",

  "characters_needed": [
    {{
      "name": "string",
      "is_new": true,
      "description": "physical appearance, colour palette, personality — 2-3 sentences"
    }}
  ],

  "shots": [
    {{
      "sequence": 1,
      "description": "one plain English sentence — for human review",
      "emotional_tone": "one phrase — the feeling this shot carries",
      "cinematic_reference": "1-2 animated films whose visual language fits this shot",

      "image_prompt": "[STYLE], [emotional tone], [visual reference style], [CHAR:name] if present, [composition], [lighting], [depth], [camera angle], [atmosphere]",

      "video_prompt": "[camera movement], [what moves and how], [duration], [what the shot ends on]",

      "motion_intent": "still|pan_in|pan_out|pan_side|zoom_in|zoom_out|hold",
      "sound_design": "ambient + any signature sound + music note for this beat",

      "transition_to_next": "cut|fade|dissolve|match_frame",

      "model": "wan|seedance|kling|veo-lite",
      "duration_sec": 5,
      "dialogue": null,
      "characters_used": ["name1"]
    }}
  ]
}}

MODEL RULES — assign the right tool per shot type:
- "kling"     → action: running, jumping, flying, animals in fast motion
- "seedance"  → character focus: close-ups, reactions, talking, gentle movement
- "wan"       → environment: establishing shots, backgrounds, no character needed
- "veo-lite"  → magic only: max 2 per episode, for sparkles/VFX/transformations

duration_sec must be one of: 5, 6, 8, 10
"""


def _extract_json(text: str) -> dict[str, Any]:
    text = text.strip()
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        pass
    start = text.find("{")
    end = text.rfind("}")
    if start >= 0 and end > start:
        return json.loads(text[start : end + 1])
    raise ValueError("Model did not return parseable JSON")


def plan_episode(raw_story: str, existing_characters: list[dict[str, Any]]) -> dict[str, Any]:
    """
    Calls Claude via OpenRouter. Returns parsed JSON shot plan.
    existing_characters: rows from characters table (name, description, …).
    """
    api_key = os.environ.get("OPENROUTER_API_KEY")
    if not api_key:
        raise RuntimeError("OPENROUTER_API_KEY is not set")

    narrator = os.environ.get("NARRATOR_NAME", "Mini").strip() or "Mini"
    model = os.environ.get("OPENROUTER_MODEL", "anthropic/claude-3-5-haiku")
    payload = {
        "model": model,
        "temperature": 0.4,
        "max_tokens": 4096,
        "messages": [
            {"role": "system", "content": _system_prompt(narrator, existing_characters)},
            {
                "role": "user",
                "content": f"Here is the story to adapt into an episode:\n\n{raw_story}",
            },
        ],
    }
    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json",
    }
    response = requests.post(
        "https://openrouter.ai/api/v1/chat/completions",
        headers=headers,
        json=payload,
        timeout=90,
    )
    if response.status_code >= 400:
        raise RuntimeError(f"OpenRouter error {response.status_code}: {response.text}")

    data = response.json()
    choices = data.get("choices") or []
    if not choices:
        raise RuntimeError("OpenRouter returned no choices")
    msg_content = choices[0].get("message", {}).get("content")
    if isinstance(msg_content, list):
        parts: list[str] = []
        for item in msg_content:
            if isinstance(item, dict) and item.get("type") == "text":
                parts.append(item.get("text", ""))
        combined = "\n".join(parts).strip()
    else:
        combined = str(msg_content or "").strip()

    result = _extract_json(combined)
    if not isinstance(result, dict) or not isinstance(result.get("shots"), list):
        raise ValueError("Model JSON missing required 'shots' list")
    return result


def slugify_name(name: str) -> str:
    s = (name or "").lower().strip()
    s = re.sub(r"[^a-z0-9]+", "-", s)
    return s.strip("-") or "character"
